services:
  aluraidentity6api:
    image: aluraidentity6api
    build:
      context: .
      dockerfile: AluraIdentity6Api/Dockerfile

  db:
      image: postgres:15
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: aluraidentity6api
      ports:
        - "5432:5432"
      volumes:
        - ./AluraIdentity6Api/Infra/Data/Database/Migrations/schema.sql:/docker-entrypoint-initdb.d/init.sql
        - pgdata:/var/lib/postgresql/data

networks:
    aluraidentity6api-network:
        driver: bridge    
  
volumes:
    pgdata: