services:
  aluraidentity6api:
    image: ${DOCKER_REGISTRY-}aluraidentity6api
    build:
      context: .
      dockerfile: AluraIdentity6Api/Dockerfile

  db:
      image: postgres:15
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
